/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyGradleProject;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import Service.UserDetailsServiceImpl;


@SpringBootApplication
class Library {

	
   public static void main(String[] args) {
	   SpringApplication.run(Library.class,args);
   }
   
   @Bean
   public BCryptPasswordEncoder bCryptPasswordEncoder() {
       return new BCryptPasswordEncoder();
   }
   
   

}
